#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 KernelSight AI
"""
Real-time Signal Monitor

Displays live semantic signals being generated by KernelSight AI.
Run this while the main system is running to see what it's detecting.
"""

import sqlite3
import time
import sys
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent / "data" / "kernelsight.db"


def clear_screen():
    """Clear terminal screen."""
    print("\033[2J\033[H", end="")


def format_timestamp(ns_timestamp):
    """Convert nanosecond timestamp to readable format."""
    try:
        # Convert nanoseconds to seconds
        timestamp_s = ns_timestamp / 1_000_000_000
        dt = datetime.fromtimestamp(timestamp_s)
        return dt.strftime("%H:%M:%S")
    except:
        return "N/A"


def get_signal_stats(conn):
    """Get signal statistics."""
    cursor = conn.cursor()
    
    # Total signals
    total = cursor.execute("SELECT COUNT(*) FROM signal_metadata").fetchone()[0]
    
    # By type
    by_type = cursor.execute("""
        SELECT signal_type, COUNT(*) as count
        FROM signal_metadata
        GROUP BY signal_type
        ORDER BY count DESC
    """).fetchall()
    
    # By severity
    by_severity = cursor.execute("""
        SELECT severity, COUNT(*) as count
        FROM signal_metadata
        GROUP BY severity
        ORDER BY 
            CASE severity
                WHEN 'critical' THEN 1
                WHEN 'high' THEN 2
                WHEN 'medium' THEN 3
                WHEN 'low' THEN 4
            END
    """).fetchall()
    
    return total, by_type, by_severity


def get_recent_signals(conn, limit=10):
    """Get most recent signals."""
    cursor = conn.cursor()
    
    signals = cursor.execute("""
        SELECT timestamp, signal_type, severity, pressure_score, summary
        FROM signal_metadata
        ORDER BY timestamp DESC
        LIMIT ?
    """, (limit,)).fetchall()
    
    return signals


def get_data_stats(conn):
    """Get raw data collection stats."""
    cursor = conn.cursor()
    
    stats = {}
    tables = [
        ('memory_metrics', 'Memory'),
        ('load_metrics', 'Load'),
        ('network_interface_stats', 'Network'),
        ('tcp_stats', 'TCP'),
        ('block_stats', 'Block I/O'),
        ('syscall_events', 'Syscalls'),
        ('sched_events', 'Scheduler'),
        ('page_fault_events', 'Page Faults')
    ]
    
    for table, label in tables:
        try:
            count = cursor.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            stats[label] = count
        except:
            stats[label] = 0
    
    return stats


def display_dashboard(conn):
    """Display the monitoring dashboard."""
    clear_screen()
    
    print("=" * 80)
    print("KernelSight AI - Real-Time Signal Monitor".center(80))
    print("=" * 80)
    print()
    
    # Signal statistics
    total, by_type, by_severity = get_signal_stats(conn)
    
    print(f"📊 SIGNAL STATISTICS")
    print(f"   Total Signals: {total}")
    print()
    
    if by_type:
        print("   By Type:")
        for sig_type, count in by_type[:5]:
            print(f"      {sig_type:30s} {count:5d}")
    print()
    
    if by_severity:
        print("   By Severity:")
        severity_colors = {
            'critical': '🔴',
            'high': '🟠',
            'medium': '🟡',
            'low': '🟢'
        }
        for severity, count in by_severity:
            icon = severity_colors.get(severity, '⚪')
            print(f"      {icon} {severity.capitalize():20s} {count:5d}")
    print()
    
    # Data collection stats
    print("📈 DATA COLLECTION")
    data_stats = get_data_stats(conn)
    for label, count in sorted(data_stats.items()):
        if count > 0:
            print(f"   {label:20s} {count:6d} events")
    print()
    
    # Recent signals
    print("🔔 RECENT SIGNALS (Last 10)")
    print("-" * 80)
    signals = get_recent_signals(conn, 10)
    
    if signals:
        for ts, sig_type, severity, pressure, summary in signals:
            time_str = format_timestamp(ts)
            severity_icon = {'critical': '🔴', 'high': '🟠', 'medium': '🟡', 'low': '🟢'}.get(severity, '⚪')
            pressure_str = f"{pressure:.2f}" if pressure else "N/A"
            
            print(f"{time_str} {severity_icon} [{sig_type:20s}] p={pressure_str} - {summary[:40]}")
    else:
        print("   No signals yet...")
    
    print()
    print("=" * 80)
    print(f"Last updated: {datetime.now().strftime('%H:%M:%S')} | Press Ctrl+C to exit")


def main():
    """Main monitoring loop."""
    if not DB_PATH.exists():
        print(f"Error: Database not found at {DB_PATH}")
        print("Make sure the system is running and collecting data.")
        sys.exit(1)
    
    try:
        conn = sqlite3.connect(str(DB_PATH))
        
        print("Starting monitor... (updates every 2 seconds)")
        time.sleep(2)
        
        while True:
            display_dashboard(conn)
            time.sleep(2)
    
    except KeyboardInterrupt:
        print("\n\nMonitor stopped.")
        conn.close()
    
    except Exception as e:
        print(f"\nError: {e}")
        import traceback
        traceback.print_exc()


if __name__ == '__main__':
    main()
